name: Core CI workflow

on:
  pull_request:
    # Run this every time a pull request is opened, reopened, or new commits
    # are pushed to it.
    types: [opened, synchronize, reopened]
  push:
    # Run this every time a commit goes to main
    branches: [main]
jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      # Set Contentful env
      - shell: bash
        env: 
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
        run: |
          export "$CONTENTFUL_SPACE_ID"
          export "$CONTENTFUL_PREVIEW_TOKEN"
          export "$CONTENTFUL_ACCESS_TOKEN"
          export "$CONTENTFUL_MANAGEMENT_TOKEN
          
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up node + npm
      - uses: actions/setup-node@v3

      # Install packages
      - name: NPM install
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build the app, ensure typecheck passes
        run: npm run build
